### PR TITLE
Add multi-scale area and scatter plot examples

### PR DESCRIPTION
**Pull request by mmore500**
Hi @holtzy --

Amazing resource you've helped the community build up. Thanks for everything you've put into designing and organizing!

This pull request contributes two notebooks, one to the examples section of the scatter plot page and the other to the area plots page examples. 

Here are the plots constructed in each notebook:
image
image

The first is an area plot lattice showing rain gauge readings over the course of a month. The second is a scatter plot lattice comparing the demographics of the top ultra-wealthy within different industries. Both plots use the `outset` library to compose zoom panels highlighting different aspects of the data. *(fyi -- I'm the library author, figured this would be a great resource to be a part of!)*

Did my best to make sure to fill in all necessary details for a smooth deploy --- if there's anything needing a fix let me know and I'll get it sorted. :+1:

### CODE REVIEW

**Comment by mmore500** [comment]
Any word on this? Or anything I can do on my end to assist in review or prep?

**Comment by holtzy** [comment]
Hi @mmore500 ,

Thanks so much!
I'm just back from long term leaves. Give me a bit of time to check this out!

**Comment by mmore500** [comment]
sounds good, and if there's anything that needs to be tweaked to clean things up or interface with the rest of the site let me know! :) Matthew

**Comment by holtzy** [comment]
thanks @mmore500,

I just merged the PR. @JosephBARBIERDARNAL is gonna integrate it to the gallery in a subsequent PR

**Pull request merged**
